title: Xi Wang's Homepage
page-top-title: Xi Wang
top-section-bg-text: GIS&RS, Sustainable Urban Grey-Green Infrastructure
home-subtitle: Xi Wang&ensp;|&ensp;王玺
copyright-text: '&copy; Xi Wang 2025-2026. All Rights Reserved.'
